spring:
  zipkin:
    base-url: https://zipkin.socshared.ml/
    service:
      name: ${spring.application.name}
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false

feign:
  gateway:
    url: http://localhost:8083/