spring:
  zipkin:
    base-url: http://zipkin:9411/
    service:
      name: ${spring.application.name}
  main:
    allow-bean-definition-overriding: true

facebook:
  redirect:
    uri: https://socshared.ml/connect/fb
  adapter:
    id: fb-adapter-prod
